DROP TABLE IF EXISTS installation;
DROP TABLE IF EXISTS log_message_argument;
DROP TABLE IF EXISTS log_message;
DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS stored_file;